### ISSUE TITLE
When Change Port or use .env Is not Working

### ISSUE THREAD

**Issue by ysh3436** [dnwjn/palworld-server-watcher#1]
![image](https://github.com/dnwjn/palworld-server-watcher/assets/13271439/418212eb-2c98-4c82-b140-002375c8b608)
Cannot connect Server And dosen't restart palworld container

**Comment by dnwjn** [comment]
@ysh3436 Can you share your `.env` file, except from the sensitive information?

**Comment by ysh3436** [comment]
> @ysh3436 Can you share your `.env` file, except from the sensitive information?

here is more infomation

TZ=Asia/Seoul
PLAYERS=16
PORT=1248
PUID=1000
PGID=1000
MULTITHREADING=true
COMMUNITY=false
PUBLIC_IP=
PUBLIC_PORT=
SERVER_NAME=World of Pals
SERVER_DESCRIPTION=World of Pals
SERVER_PASSWORD=
ADMIN_PASSWORD=
UPDATE_ON_BOOT=true
RCON_ENABLED=true
RCON_PORT=30005
QUERY_PORT=27015
BACKUP_ENABLED=true
DELETE_OLD_BACKUPS=true
OLD_BACKUP_DAYS=30
BACKUP_CRON_EXPRESSION=55 4 * * *
AUTO_UPDATE_ENABLED=true
AUTO_UPDATE_CRON_EXPRESSION=0 * * * *
AUTO_UPDATE_WARN_MINUTES=30
AUTO_REBOOT_ENABLED=true
AUTO_REBOOT_WARN_MINUTES=3
AUTO_REBOOT_CRON_EXPRESSION=00 5 * * *

DIFFICULTY=None
DAYTIME_SPEEDRATE=1.000000
NIGHTTIME_SPEEDRATE=1.000000
EXP_RATE=1.000000
PAL_CAPTURE_RATE=1.000000
PAL_SPAWN_NUM_RATE=1.000000
PAL_DAMAGE_RATE_ATTACK=1.000000
PAL_DAMAGE_RATE_DEFENSE=1.000000
PLAYER_DAMAGE_RATE_ATTACK=1.000000
PLAYER_DAMAGE_RATE_DEFENSE=1.000000
PLAYER_STOMACH_DECREASE_RATE=1.000000
PLAYER_STAMINA_DECREASE_RATE=1.000000
PLAYER_AUTO_HP_REGEN_RATE=1.000000
PLAYER_AUTO_HP_REGEN_RATE_IN_SLEEP=1.000000
PAL_STOMACH_DECREASE_RATE=0.1
PAL_STAMINA_DECREASE_RATE=0.1
PAL_AUTO_HP_REGEN_RATE=1.000000
PAL_AUTO_HP_REGEN_RATE_IN_SLEEP=1.000000
BUILD_OBJECT_DAMAGE_RATE=1.000000
BUILD_OBJECT_DETERIORATION_DAMAGE_RATE=1.000000
COLLECTION_DROP_RATE=1.000000
COLLECTION_OBJECT_HP_RATE=1.000000
COLLECTION_OBJECT_RESPAWN_SPEED_RATE=1.000000
ENEMY_DROP_ITEM_RATE=1.000000
DEATH_PENALTY=Item
ENABLE_PLAYER_TO_PLAYER_DAMAGE=False
ENABLE_FRIENDLY_FIRE=False
ENABLE_INVADER_ENEMY=True
ACTIVE_UNKO=False
ENABLE_AIM_ASSIST_PAD=True
ENABLE_AIM_ASSIST_KEYBOARD=False
DROP_ITEM_MAX_NUM=3000
DROP_ITEM_MAX_NUM_UNKO=100
BASE_CAMP_MAX_NUM=128
BASE_CAMP_WORKER_MAXNUM=15
DROP_ITEM_ALIVE_MAX_HOURS=1.000000
AUTO_RESET_GUILD_NO_ONLINE_PLAYERS=False
AUTO_RESET_GUILD_TIME_NO_ONLINE_PLAYERS=72.00000
GUILD_PLAYER_MAX_NUM=5
PAL_EGG_DEFAULT_HATCHING_TIME=2.00000
WORK_SPEED_RATE=1.000000
IS_MULTIPLAY=False
IS_PVP=False
CAN_PICKUP_OTHER_GUILD_DEATH_PENALTY_DROP=False
ENABLE_NON_LOGIN_PENALTY=True
ENABLE_FAST_TRAVEL=True
IS_START_LOCATION_SELECT_BY_MAP=True
EXIST_PLAYER_AFTER_LOGOUT=False
ENABLE_DEFENSE_OTHER_GUILD_PLAYER=False
COOP_PLAYER_MAX_NUM=4
REGION=
USEAUTH=True
BAN_LIST_URL=https://api.palworldgame.com/api/banlist.txt
DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/
DISCORD_CONNECT_TIMEOUT=30
DISCORD_MAX_TIMEOUT=30
DISCORD_PRE_UPDATE_BOOT_MESSAGE="Server is updating..."
DISCORD_POST_UPDATE_BOOT_MESSAGE="Server update complete!"
DISCORD_PRE_START_MESSAGE= "Server is started!"
DISCORD_PRE_SHUTDOWN_MESSAGE=	"Server is shutting down..."
DISCORD_POST_SHUTDOWN_MESSAGE=	"Server is stopped!"

**Comment by dnwjn** [comment]
@ysh3436 It seems you're missing the following property on your server container:

```
network_mode: service:watcher
```

(See also [docker-compose.yml.example](https://github.com/dnwjn/palworld-server-watcher/blob/main/docker-compose.yml.example) for an example config)

Can you add that and try again?

**Comment by dnwjn** [comment]
I'm closing this as it's been a week without activity. @ysh3436 don't hesitate to open a new issue if you're having problems!
