### ISSUE TITLE
[feature request] Controlling docker via discord bot

### ISSUE THREAD

**Issue by chowhi123** [dnwjn/palworld-server-watcher#2]
Hi,
I don't know if this is possible but just a suggestion. Since it already integrate docker socket, it would be awesome if we can use discord bot to control the instance.

Following is the project that thijsvanloef contributed to control docker via discord bot. Could this project help to achieve this goal?

https://github.com/allenrkeen/server-bot?tab=readme-ov-file

**Comment by dnwjn** [comment]
Hi @chowhi123! Thank you for your suggestion! Could you give me an example of functionality that would be useful to have in my package, instead of running the package you linked separately?

**Comment by chowhi123** [comment]
First, I can't thank you enough for such an awesome project. This project provides such a huge benefit in controlling palworld docker server instance. It uses RCON to grab user presence and monitors the 8211 port to wake up the instance. If following bot function is added instead of running separately, it will provide alternative way to interact with the palworld server when RCON is broken like v0.15 patch. It will give user control back when watcher function is unable to correctly start stop the server!
Thank you again!

**Comment by dnwjn** [comment]
@chowhi123 Thank you for the kind words! I'm happy to hear something I initially made for myself also serves others well :)

I think you have a great point there! I see the value in that. I'm gonna start working on that feature, and I'll make sure to update you here when that's implemented!

**Comment by dnwjn** [comment]
Hi @chowhi123, I've just added a Discord integration! It's available in v0.1.3. For steps on how to set it up, please refer to the readme.

If you come across any issues, don't hesitate to open a new ticket!

**Comment by chowhi123** [comment]
> Hi @chowhi123, I've just added a Discord integration! It's available in v0.1.3. For steps on how to set it up, please refer to the readme.
> 
> If you come across any issues, don't hesitate to open a new ticket!

So many thanks! I will check out right away!

**Comment by dnwjn** [comment]
> > Hi @chowhi123, I've just added a Discord integration! It's available in v0.1.3. For steps on how to set it up, please refer to the readme.
> > If you come across any issues, don't hesitate to open a new ticket!
> 
> So many thanks! I will check out right away!
> 
> Edit-This is working amazing!

So glad to hear! 😄
