### ISSUE TITLE
[Feature Request] Delayed shutdown

### ISSUE THREAD

**Issue by chowhi123** [dnwjn/palworld-server-watcher#5]
As the popularity of the Palworld is fading away, watcher provides a lot of benefits. But because it immediately shutdown the server after all the player leaves. It doesn't allow 1 hour timer for the boss monster spawn to finish. It would be beneficial if we had a delay shutdown (DELAYED_SHUTDOWN) as env variable to control how long watcher to wait to close the server when eveybody leaves.

Thank you!

**Comment by dnwjn** [comment]
Hey @chowhi123! Thank you so much for your feature request. I think it would make for a great addition to the watcher! I will let you know when it's implemented :)

**Comment by dnwjn** [comment]
@chowhi123 Hi there, this feature has been added in the latest release, v0.2.0!

**Comment by chowhi123** [comment]
Thank you! You are amazing!
