### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by ctoonzmk** [dnwjn/palworld-server-watcher#7]
When running docker-compose up I get the below error
![image](https://github.com/dnwjn/palworld-server-watcher/assets/15790207/ca6f8972-d817-4083-8df4-8e21fbd16294)

When checking the docker logs the error is:
exec ./entrypoint.sh: exec format error

below is my docker-compose file
![image](https://github.com/dnwjn/palworld-server-watcher/assets/15790207/7fc1f807-51e7-46d5-ae41-a69418e0ed0e)

**Comment by dnwjn** [comment]
Hi @ctoonzmk and thank you for your issue!

Based on what I'm finding about the error you're experiencing is that it might be an architecture issue. The image is built for:

```
"Architecture": "amd64"
```

Could it be that your architecture is not `amd64`?
